[toolchain]
anchor_version = "0.30.1"
solana_version = "2.1.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
anchor_test = "GFtGWNCTTPvw6Nem59NuWHShewVAgY91DJLWL9MWLhBr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
